version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=copperway_carwash
      - DB_USER=copperway_user
      - DB_PASS=copperway_password

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: copperway_carwash
      MYSQL_USER: copperway_user
      MYSQL_PASSWORD: copperway_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: copperway_user
      PMA_PASSWORD: copperway_password
    depends_on:
      - db

volumes:
  mysql_data:
